In [1]:
### Building your own Modules

In [2]:
import pandas as pd

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import edhec_risk_kit as erk

returns = erk.get_ffme_returns()

c:\Users\beall\OneDrive\Documents\Repos\risk\edhec\01 Intro to Portfolio Construction and Analysis\Mod-01\edhec_risk_kit.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  me_m = pd.read_csv(

In [5]:
returns.head()

        SmallCap  LargeCap
192607   -0.0145    0.0329
192608    0.0512    0.0370
192609    0.0093    0.0067
192610   -0.0484   -0.0243
192611   -0.0078    0.0270

In [6]:
erk.drawdown(returns["SmallCap"])

              Wealth         Peaks  Drawdown
192607  9.855000e+02  9.855000e+02  0.000000
192608  1.035958e+03  1.035958e+03  0.000000
192609  1.045592e+03  1.045592e+03  0.000000
192610  9.949854e+02  1.045592e+03 -0.048400
192611  9.872245e+02  1.045592e+03 -0.055822
...              ...           ...       ...
201808  2.298938e+09  2.298938e+09  0.000000
201809  2.260316e+09  2.298938e+09 -0.016800
201810  2.033832e+09  2.298938e+09 -0.115317
201811  1.959597e+09  2.298938e+09 -0.147608
201812  1.659583e+09  2.298938e+09 -0.278109

[1110 rows x 3 columns]

In [7]:
erk.drawdown(returns["SmallCap"])["Drawdown"].min()

np.float64(-0.8330007793945303)

In [ ]:
# Convert the 197501 integers into proper monthly period objects
returns.index = pd.to_datetime(returns.index, format="%Y%m").to_period("M")

In [12]:
erk.drawdown(returns["1975":]["SmallCap"])["Drawdown"].min()

np.float64(-0.6312068077252386)